# [payload]
# maxSize = 10240 # Maximum payload size in bytes
# [payload.files]
# maxFileSize = 5242880 # Maximum file size in bytes
# saveFolder = "images" # Folder to save the images to, within the api folder
# allowedFileTypes = {'image/jpg' = 'jpg', 'image/jpeg' = 'jpg', 'image/png' = 'png', 'image/webp' = 'webp', 'image/avif' = 'avif' } # Allowed image format. The property name is the MIME type of the format, and the value the extension name.

# [adminUser]
# email = 'admin@groupomania.com' # Email of the administrator user. When starting the server, if no user has this email, it will be created witha random password.