[cors]
origin = true
methods = ["GET", "POST", "PUT", "DELETE", "OPTION"]
allowedHeaders = ["Origin", "X-Requested-With", "Accept", "Content-Type", "Authorization"]
# exposedHeaders
# credentials
# maxAge

# [payload]
# maxSize = 10240

# [password]
# minLength = 8
# minLowercase = 1
# minUppercase = 1
# minNumbers = 1
# minSymbols = 1

# [adminUser]
# roleId = 1
# email = 'admin@groupomania.com'