[cors]
origin = true
methods = ["GET", "POST", "PUT", "DELETE", "OPTION"]
allowedHeaders = ["Origin", "X-Requested-With", "Accept", "Content-Type", "Authorization"]
# exposedHeaders
# credentials
# maxAge
